#!/bin/bash
USAGE=$(cat << END
USAGE: $0 [-h|--help] DAY
DESCRIPTION: Solve the days puzzle by running ./{DAY}/solve.py
ARGUMENTS:
    DAY: The day to solve, integer between 1 and 25

END
)

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "$USAGE"
    exit 0
fi
if [ $# -ne 1 ]; then
    echo "$USAGE"
    exit 1
fi
if [ $1 -lt 1 ] || [ $1 -gt 25 ]; then
    echo "Error: DAY must be an integer between 1 and 25"
    echo "$USAGE"
    exit 1
fi
DAY="$1"
DIR_PROJECT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR_DAY="${DIR_PROJECT}/$(printf "%02d" $DAY)"
DIR_ENV_NAME='.venv'
DIR_ENV='$DIR_PROJECT/$DIR_ENV_NAME'
# Check if the venv directory exists
if [ ! -d "$DIR_ENV" ]; then
    python3 -m venv $DIR_ENV
    python3 -m pip install -r $DIR_PROJECT/requirements.txt
fi

# Run the solve.py script in the day's directory,
# ensure early exits deactivate, same for errors, and term/kill signals
trap "deactivate; exit" SIGINT SIGTERM ERR EXIT
# Activate the virtual environment
source $DIR_ENV/bin/activate
# Run the solve.py script
python $DIR_DAY/solve.py
# Deactivate the virtual environment
deactivate
